### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by ALee008** [tguelcan/MovieHub#2]
Hello,
I just started learning Svelte and am trying to run your project. After `npm install` I am call `npm run dev`, but this is the error I'm receiving:

`Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.each (/Users/xxx/WebstormProjects/MovieHub/node_modules/svelte/internal/index.js:1710:31)
    at index.svelte:44:9
    at Object.$$render (/Users/xxx/WebstormProjects/MovieHub/node_modules/svelte/internal/index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at eval (/src/routes/__layout.svelte:37:94)
    at Object.$$render (/Users/xxx/WebstormProjects/MovieHub/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/Users/xxx/WebstormProjects/MovieHub/node_modules/svelte/internal/index.js:1745:22)
    at Object.render (/Users/xxx/WebstormProjects/MovieHub/node_modules/svelte/internal/index.js:1753:26)
    at render_response (file:///Users/xxx/WebstormProjects/MovieHub/.svelte-kit/runtime/server/index.js:1198:28)`

Any suggestions or ideas what I'm doing wrong?
npm version: 9.2.0
node version: 18.12.1
svelte-cli version: 3.0.0

Thank you.

**Comment by marksteven** [comment]
Getting similar error.
Instructions say
npm init svelte@next my-app
which gives you a skeleton project are you then supposed to git clone this repository into same folder or something else.
Like Alee I too am learning this and does not seem clear Thanks
